apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-dev

resources:
  - ../../../base

namePrefix: app-a3-

commonLabels:
  tenant: tenant-a
  app: app-a3
  environment: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: AppA3-dev.agent.opsera.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: AppA3-dev.agent.opsera.io
    target:
      kind: Ingress
      name: app

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=dev
      - TENANT=tenant-a
      - APP_NAME=app-a3





