apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tenant-a-app1

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: app1
  app.kubernetes.io/component: mcp-agent
  app.kubernetes.io/part-of: tenant-a
  opsera.io/tenant: tenant-a
  opsera.io/app: app1

